### ISSUE TITLE
New Bot: autosynth managed files bot

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1034]
synthtool manages a synth.metadata file which optionally tracks generated files. People often try to manually update a file managed by synthtool templates.

We can have a bot that warns a PR if you are modifying a file that is managed by synthtool templates.

**Comment by tbpg** [comment]
Can we disconnect this from autosynth? If any autogenerated file (identified by some string in the file or a config file) is edited by a human, give a warning.

**Comment by chingor13** [comment]
A string in the file might not be feasible as the only method. Some files (like .json files) cannot support any kind of comments.

A config file could be an option, the challenge is that the generator process must also maintain the list. Synthtool does do this for yoshi-managed repositories.

I could possibly see a config for something like `.github/generated-file-bot.yaml`:

```yaml
# list of explicit files
generatedFiles:
- file1.txt
- file2.txt
externalManifests:
- file: synth.metadata
  type: json
  expression: .generatedFiles
```
