### ISSUE TITLE
Auto-label priorities

### ISSUE THREAD

**Issue by 0xSage** [googleapis/repo-automation-bots#1238]
I was thinking about extending auto-label bot to also label priorities based on `other labels` and `title keywords` (or `bug creator`). For example, if
i) a user creates a `type: bug` issue => P1
ii) automations (yoshi-automation and renovatebot) create issues/PRs => P1/P2
_Side note: It's nice that build cop already auto labels P1 for issues it creates._

A lot of our team automations depends on priorities. And cmiiw, we're required to label priorities before issues are considered as "triaged" or moved out of OOSLO?

How it might look in configurations: 
```yaml
product: ... existing config
language: ..existing config
path: ..existing config
priority: 
  default:
      pullrequest: true
      issue: true
      priority: 2
  label_triggered:
      labels: ['type: bug']
      ...
  title_triggered / sender_triggered: ...
```

If there are no objections I'll go ahead and implement this
