### ISSUE TITLE
Cannot automatically configure more than one cron

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#1544]
If a bot needs more than one cron, we cannot currently support this via our infrastructure as code (we look for a single `cron` file at the bot's root).

**Comment by chingor13** [comment]
Proposal: use a yaml format to allow more customization here

```yaml
cron:
 - name: 'name for identification'
   description: 'some description'
   schedule: 'cron syntax here'
   # extra parameters to pass in the scheduled job
   params:
     # bot installation id, not really a secret or confidential info
     installation_id: 12345
     cron_org: googleapis
```
