### ISSUE TITLE
owl bot: copies from googleapis-gen to mono repos will merge/accumulate

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1691]
As discussed with @jskeet 

With a single .OwlBot.yaml file like this:
```yaml
deep-copy-regex:
  - source: /a/b/c
    dest: ...
  - source: /x/y/z
    dest: ...
```

Imagine two commits in googleapis-gen:
1. modifies /a/b/c
2. modifies /x/y/z

If Owl Bot generates the code for 2 before the maintainer has merged 1, then the generated PR for 2 will also contain the changes for 1.  What's worse, if commit 1 contains a breaking change that should not be merged, it's going to be a nasty chore to remove it from all subsequent pull requests generated by Owl Bot.  That's not what Jon Skeet wants, nor can I imagine anyone wanting this behavior.

CC @dazuma
