### ISSUE TITLE
FR: Allow Docker entry-point or cmd to be specified in .OwlBot.yaml

### ISSUE THREAD

**Issue by jskeet** [googleapis/repo-automation-bots#1692]
Currently, I need to create a Docker image for OwlBot to run.

All I want my Docker image to do is run a bash script. Currently that means I have to have a Dockerfile of the form:

```sh
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
CMD ["tools/owlbot-postprocess.sh"]
```

... then build that as a Docker image and publish it.

I'd really prefer to be able to skip the Dockerfile, and have a .OwlBot.yaml file of:

```yaml
docker:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
  cmd: tools/owlbot-postprocess.sh
```

(I'm aware there are [differences between ENTRYPOINT and CMD](https://www.ctl.io/developers/blog/post/dockerfile-entrypoint-vs-cmd/) but I don't have strong opinions - I'd be happy enough with an entry-point array specified in the YAML instead. The exact format doesn't bother me nearly as much as not having to have a Dockerfile and publish a docker image somewhere.)
