### ISSUE TITLE
feat(sync-repo-settings): add org level configs

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1884]
Background:

Now sync-repo-settings has the global config in the source code.
It is great if we can put org level config in `ORG/.github/` repo.

The caveat is that, org level config might have a different schema from the repo level settings (probably object keyed by language or sth), so a simple falling back to `.github` repo strategy doesn't work.

Maybe we can have a schema that allows a list and the config at the same time, or we can have a different config file name.

**Comment by tmatsuo** [comment]
My proposal:

1. Have a different schema and filename for org level config.
2. Modify the function for fetching config
    2-1. First try to fetch the repo config
    2-2. Upon 404, it will fetch the org level config from the `.github` repo and try to get the config from the inferred language
3. We still need to fallback to the global config
4. Once we have org level configs both for googleapis and GCP, we can remove the global config in the source code.

@JustinBeckwith How does it sound?

**Comment by JustinBeckwith** [comment]
In general, that sounds great.  A big open question in my mind is how flexible we want to be in terms of how users select which repositories they want a given config to apply to.  Today, we just provide per-language selection.  I was experimenting with a more open format that let users filter on any property in the repo (is it private, is it archived, does it have a repository topic, regex matches on names, etc).  The problem is, that gets *complicated* very quickly.  I don't know how far we want to go with config selection in the org level config, but your approach is generally where I was trying to go.

**Comment by tmatsuo** [comment]
I see.
The suggested selector has `org:googleapis is:public archived:false`.

For organization, it is determined by the `.github` repo's organization.
For public/private, do we ever want to sync with private repos?
For archived repo, do we ever want to sync with archived repos?

Actually now the scheduler job is skipping archived repository.

So maybe we can allow any key, starting with `language:` selectors?

```json
{
  "language:java": { //Java config here },
}
```

Then later, we can add other keys when necessary, something like?

```json
{
  "archived:true": { //Config for archived repo here },
}
```

**Comment by tmatsuo** [comment]
Or we can still preserve the similar format suggested in https://github.com/googleapis/.github/pull/10/files#diff-3441059af11c9bb893d42a2eae9f0782ffeb3fb4dcc1da0a98d93a1c1f2bc250

```yaml
- name: "java"
  selector: "language:java"
  config:
    branchProtectionRules: #...
- name: "python"
  selector: "language:python"
  config:
    branchProtectionRules: #...
- name: "nodejs"
  selector: "language:javascript language:typescript"
  config:
    branchProtectionRules: #...
```

@JustinBeckwith Sounds good?

**Comment by tmatsuo** [comment]
My plan:

1. Make some changes to bot-config-utils.
    1-1. Add an option for not falling back to `.github` repo config to `getConfig` (because sync-repo-settings will have different schema for repo and org level config)
    1-2. Add an option for providing multiple schema files so that we can use external definition.
2. Then first migrate the current config related code to bot-config-utils
3. Then add org level config and custom selector logic

**Comment by tmatsuo** [comment]
Migrating to bot-config-utils with #1910 

For generic selector, maybe we can use a library like this:
https://www.npmjs.com/package/easy-object-selector

and use the schema like this(only the selector part):
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "list of selector",
  "description": "Schema for defining a list of selector",
  "additionalProperties": false,
  "type": "array",
  "items": {
    "type": "array",
    "items": [
      {"type": "string"},
      {"enum": ["eq", "ne", "anyof", "regex"]},
      {"AnyOf": [
        {"type": "string"},
        {"type": "number"},
        {"type": "boolean"}
        {"type": "array", "items": { "type": "string" }}
      	]
      }
    ],
    "additionalItems": false
  }
}
```

Then org config:
```yaml
- name: "java"
  selectors:
    - ["private", "eq", false]
    - ["archived", "eq", false]
    - ["owner.login", "anyof", ["GoogleCloudPlatform", "googleapis"]]
    - ["language", "eq", "java"]
  config:
    branchProtectionRules: #...
- name: "python"
  selectors:
    - ["private", "eq", false]
    - ["archived", "eq", false]
    - ["owner.login", "anyof", ["GoogleCloudPlatform", "googleapis"]]
    - ["language", "eq", "python"]
  config:
    branchProtectionRules: #...
- name: "nodejs"
  selectors:
    - ["private", "eq", false]
    - ["archived", "eq", false]
    - ["owner.login", "anyof", ["GoogleCloudPlatform", "googleapis"]]
    - ["language", "eq", "python"]
  config:
    branchProtectionRules: #..
```
