### ISSUE TITLE
release-please: support wildcard pattern in branches

### ISSUE THREAD

**Issue by mdvorak** [googleapis/repo-automation-bots#5044]
Currently, release-please config requires exact branch names to be listed. We could use wildcard, so config does not have to be modified every time new branch is created/deleted.

Idea:
```yaml
handleGHRelease: true
manifest: true
branches:
  - branch: release/*
    handleGHRelease: true
    manifest: true
```

Change itself should be fairly easy, just replace strict comparison in `findBranchConfiguration` with pattern matching.

Would you be willing to merge a PR for this feature?
