### ISSUE TITLE
How to conditionally run steps and get the tag information using this bot instead of the github-action

### ISSUE THREAD

**Issue by danielo515** [googleapis/repo-automation-bots#5206]
Hello.
I'm trying to use this bot instead of the github action (google-github-actions/release-please-action@v3) because this bot will trigger my other workflows, and I need them to keep things in sync.
However, I'm not sure how I will read the created release tag, and conditionally run steps if I remove the github action.
For example, given this workflow:

```yaml
name: Release
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Release Please
              uses: google-github-actions/release-please-action@v3
              id: release
              with:
                  command: manifest
                  token: ${{secrets.GITHUB_TOKEN}}
            - name: Upload Release Assets
              if: ${{ steps.release.outputs.release_created }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TAG_NAME: ${{ steps.release.outputs.tag_name }}
              run: |
                  gh release upload $TAG_NAME main.js manifest.json styles.css
```

How will I accomplish the same by removing the action and just using this bot?
